// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Stocks.Touch {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("AddStockView")]
	public partial class AddStockView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextField __mt_symbolName;
		
		private MonoTouch.UIKit.UIButton __mt_addBtn;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("symbolName")]
		private MonoTouch.UIKit.UITextField symbolName {
			get {
				this.__mt_symbolName = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("symbolName")));
				return this.__mt_symbolName;
			}
			set {
				this.__mt_symbolName = value;
				this.SetNativeField("symbolName", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("addBtn")]
		private MonoTouch.UIKit.UIButton addBtn {
			get {
				this.__mt_addBtn = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("addBtn")));
				return this.__mt_addBtn;
			}
			set {
				this.__mt_addBtn = value;
				this.SetNativeField("addBtn", value);
			}
		}
	}
}
